version: "3.9"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                PHP_VERSION: 8.3
                FRANKENPHP_VERSION: latest
                COMPOSER_VERSION: latest
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'

        volumes:
            - .:/var/www/html

        ports:
            - "8000:8000"
        depends_on:
            - db
            - redis
        networks:
            - laravel_network

    db:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: root_secret
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - laravel_network

    redis:
        image: redis:alpine
        ports:
            - "6379:6379"
        networks:
            - laravel_network

    phpmyadmin:
        image: phpmyadmin:latest
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: root_secret
        ports:
            - "8080:80"
        depends_on:
            - db
        networks:
            - laravel_network

volumes:
    db_data:

networks:
    laravel_network:
        driver: bridge
